# Generated by Django 6.1 on 2026-08-27 06:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('primary_event', models.CharField(choices=[('SPRINTS', 'Sprints (100m-400m)'), ('MIDDLE', 'Middle Distance (800m-1500m)'), ('LONG', 'Long Distance (5000m-Marathon)')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INJURED', 'Injured'), ('RESTING', 'Resting'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RacePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(choices=[('100m', '100m'), ('200m', '200m'), ('400m', '400m'), ('800m', '800m'), ('1500m', '1500m'), ('5000m', '5000m'), ('10km', '10km'), ('21.1km', '21.1km')], max_length=10)),
                ('date', models.DateField()),
                ('recorded_time_seconds', models.DecimalField(decimal_places=2, help_text='Race finish time in seconds (e.g., 112.40 for 1:52.40)', max_digits=8)),
                ('asa_standard_seconds', models.DecimalField(decimal_places=2, help_text='ASA National Qualifying Target in seconds', max_digits=8)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_performances', to='core.athlete')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('session_type', models.CharField(choices=[('TRACK', 'Track Intervals'), ('LONG_RUN', 'Long Run'), ('TEMPO', 'Tempo Run'), ('STRENGTH', 'Gym / Strength'), ('RECOVERY', 'Active Recovery')], default='TRACK', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('rpe', models.PositiveIntegerField(help_text='Rate of Perceived Exertion (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.athlete')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('athlete', 'date')},
            },
        ),
    ]
