# Generated by Django 6.1 on 2026-08-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='primary_event',
            field=models.CharField(choices=[('SPRINTS', 'Sprints (100m-400m)'), ('MIDDLE', 'Middle Distance (800m-1500m)'), ('LONG', 'Long Distance (5000m-Marathon)'), ('HURDLES', 'Hurdles'), ('JUMPS', 'Jumps'), ('THROWS', 'Throws')], max_length=10),
        ),
    ]
